name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-lint:
    name: test-lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update local toolchain
      run: |
        rustup update

    - name: Toolchain info
      run: |
        cargo --version
        rustc --version
        cargo clippy --version

    - name: Run tests
      run: cd rust && cargo test 

    - name: Run lint
      run: cd rust && cargo clippy
